---
admin:
  name: Admin
  items:
    user:
      name: Login
      value: surface
      default: surface
      limits:
        maxlength: 20
    password:
      name: Password
      value: surface
      default: surface
      limits:
        maxlength: 20
network:
  name: Network
  items:
    dhcp:
      name: dhcp
      value: false
      default: true
    ip:
      name: ip
      value: 192.168.0.13
      default: 192.168.7.2
      limits:
        ipaddr: true
    mask:
      name: mask
      value: 255.255.255.0
      default: 255.255.255.0
      limits:
        ipaddr: true
    gw:
      name: gw
      value: 192.168.0.1
      default: 192.168.7.1
      limits:
        ipaddr: true
